### ISSUE TITLE
The hosting is not fully documented

### ISSUE THREAD

**Issue by stho32** [naseif/scaling-giggle-api#5]
Hey naseif,

we really need to document the server setup in a better and mostly automated way.
At the moment - when our production server dies - we have a lot to do. And probably do everything differently than the first time setup.

we started this last week but should continue until we can replace the current server really fast.

best regards,
Stefan

**Comment by naseif** [comment]
I clicked so many wrong buttons on phone lol xD

Hey Stefan, yeah you are right. I will make sure to document the process here in the _README_ for future reference. What concerns me is the automation since we are using **swizzin** to install **nginx** and **LetsEncrypt** to apply the SSL Certificate to the server. I will see if I can replace the prompt variables from the shell scripts provided by **swizzin** with the needed data and run some tests on a vm. Hopefully we will end up having a script for this as well and we officially would have automated everything for this api 👍🏼

**Comment by naseif** [comment]
This shoudl be enough for now. Next I will try to automate this whole process and see if I can get it to work

**Comment by naseif** [comment]
Hey @stho32, The nginx installation is not as simple as I expected, there is so much to configure after the installation in order for the script to work. Take a look anyway and let me know what you think.

**Comment by naseif** [comment]
This issue has been resolved. After 48d505d7e918860a64fbce6310dcaa756665fcea and e4d38438bf07ac972c0004f56042107499f4afa2 the whole process is now automated. README has been also been updated aec0581c5f5c6232011b818deea6ff93695de697 since there is no need for complex instructions anymore.
